In [1]:
import torch

In [3]:
a = torch.FloatTensor(2, 3)
b = torch.FloatTensor([3, 4, 5, 7])
print(a)
print(b)
print(type(a))
print(b.dtype)
print(b.size())
print(a.size())


tensor([[-6.9429e-18,  1.8273e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])
tensor([3., 4., 5., 7.])
<class 'torch.Tensor'>
torch.float32
torch.Size([4])
torch.Size([2, 3])


In [8]:
a = torch.IntTensor(2, 3)
b = torch.IntTensor([3, 4, 5, 7])
print(a)
print(b)
print(type(a))
print(b.dtype)
print(b.size())

tensor([[-1560275424,        1304,           0],
        [          0,           0,           0]], dtype=torch.int32)
tensor([3, 4, 5, 7], dtype=torch.int32)
<class 'torch.Tensor'>
torch.int32
torch.Size([4])


In [9]:
a = torch.rand(2, 3)
print(a)
print(type(a))
print(a.dtype)

tensor([[0.5929, 0.4951, 0.6611],
        [0.9759, 0.4121, 0.1269]])
<class 'torch.Tensor'>
torch.float32


In [10]:
a = torch.randn(2,3)
print(a)
print(type(a))
print(a.dtype)

tensor([[-0.0148,  0.4677, -0.6320],
        [-1.4807, -0.1837, -1.0102]])
<class 'torch.Tensor'>
torch.float32


In [11]:
mean = torch.arange(1, 6, dtype=torch.float)
std = torch.arange(1, 6, dtype=torch.float)
t = torch.normal(mean, std)
print(t)

tensor([-0.5052,  0.0534,  4.1326, -0.8789,  2.9691])


In [13]:
mean = 2
std = torch.arange(1, 4, dtype=torch.float)
t = torch.normal(mean, std)
print("mean:{}, std{}".format(mean, std))
print(t)

mean:2, stdtensor([1., 2., 3.])
tensor([1.7327, 1.2599, 4.6749])


In [14]:
mean = torch.arange(1, 4, dtype=torch.float)
std = 2
t = torch.normal(mean, std)
print("mean:{}, std:{}".format(mean, std))

mean:tensor([1., 2., 3.]), std:2


In [15]:
a = torch.range(1, 5, 1)
b = torch.arange(1, 5, 1)
print(a)
print(a.dtype)
print(b)
print(b.dtype)

tensor([1., 2., 3., 4., 5.])
torch.float32
tensor([1, 2, 3, 4])
torch.int64


C:\Users\魏天旗\AppData\Local\Temp\ipykernel_4516\44058219.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  a = torch.range(1, 5, 1)


In [16]:
a = torch.zeros(2,3)
b = torch.ones(2, 3, dtype = int)
print(a)
print(a.dtype)
print(a.shape)
print(b)
print(b.dtype)
print(b.size())

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.float32
torch.Size([2, 3])
tensor([[1, 1, 1],
        [1, 1, 1]])
torch.int64
torch.Size([2, 3])


In [17]:
a = torch.randn(2, 3)
print(a)

b = torch.abs(a)
print(b)

tensor([[-0.5738,  0.5927,  1.0382],
        [-2.3394, -0.6122, -1.0085]])
tensor([[0.5738, 0.5927, 1.0382],
        [2.3394, 0.6122, 1.0085]])


In [18]:
a = torch.randn(2, 3)
print(a)

b = torch.randn(2, 3)
print(b)

c = torch.add(a, b)
print(c)

print(a.add(b))
print("a.add后的a值：", a)
print(a.add_(b))
print("a.add_后的a值：", a)

d = torch.randn(2, 3)
print(d)
e = torch.add(d, 10)
print(e)

tensor([[-0.4992, -0.1330,  0.9678],
        [ 1.5093,  0.5313,  0.2497]])
tensor([[ 0.4771, -2.2336, -0.6951],
        [-1.5724, -0.8271,  1.4903]])
tensor([[-0.0220, -2.3666,  0.2727],
        [-0.0631, -0.2958,  1.7400]])
tensor([[-0.0220, -2.3666,  0.2727],
        [-0.0631, -0.2958,  1.7400]])
a.add后的a值： tensor([[-0.4992, -0.1330,  0.9678],
        [ 1.5093,  0.5313,  0.2497]])
tensor([[-0.0220, -2.3666,  0.2727],
        [-0.0631, -0.2958,  1.7400]])
a.add_后的a值： tensor([[-0.0220, -2.3666,  0.2727],
        [-0.0631, -0.2958,  1.7400]])
tensor([[-1.1498,  0.3698,  0.9983],
        [ 0.6134, -0.2678, -0.5154]])
tensor([[ 8.8502, 10.3698, 10.9983],
        [10.6134,  9.7322,  9.4846]])


In [19]:
a = torch.randn(2, 3)
print(a)

b = torch.clamp(a, -0.1, 0.1)
print(b)

tensor([[-1.0433, -0.6093, -0.5342],
        [ 0.0598,  0.5829,  1.5532]])
tensor([[-0.1000, -0.1000, -0.1000],
        [ 0.0598,  0.1000,  0.1000]])


In [20]:
a = torch.randn(2, 3)
print(a)

b = torch.randn(2, 3)
print(b)

c = torch.div(a, b)
print(c)

d = torch.randn(2, 3)
print(d)

e = torch.div(d, 10)
print(e)


tensor([[-0.6058, -1.9187,  0.3214],
        [ 0.3745,  0.3290,  1.2281]])
tensor([[ 0.2700,  0.0554, -0.9360],
        [ 1.3633, -0.6561, -0.5199]])
tensor([[ -2.2440, -34.6082,  -0.3434],
        [  0.2747,  -0.5014,  -2.3622]])
tensor([[ 1.3746, -0.7105, -0.0676],
        [-1.8075,  0.3557,  0.3320]])
tensor([[ 0.1375, -0.0711, -0.0068],
        [-0.1807,  0.0356,  0.0332]])


In [21]:
a = torch.rand(2, 3)
print(a)

b = torch.rand(2, 3)
print(b)

c = torch.mul(a, b)
print(c)

d = torch.randn(2, 3)
print(d)

e = torch.mul(d, 10)
print(e)

tensor([[0.7906, 0.4385, 0.0599],
        [0.6348, 0.1832, 0.8295]])
tensor([[0.1975, 0.3349, 0.2954],
        [0.4206, 0.1174, 0.6364]])
tensor([[0.1561, 0.1469, 0.0177],
        [0.2670, 0.0215, 0.5279]])
tensor([[ 0.5423, -0.8415,  0.6581],
        [ 2.3627, -0.3757,  0.7093]])
tensor([[ 5.4234, -8.4154,  6.5810],
        [23.6270, -3.7567,  7.0928]])


In [22]:
a = torch.randn(2, 3)
print(a)

b = torch.pow(a, 2)
print(b)

tensor([[ 0.5830, -0.1949,  1.1581],
        [ 0.3543,  0.4847,  0.4689]])
tensor([[0.3399, 0.0380, 1.3412],
        [0.1255, 0.2349, 0.2199]])


In [25]:
a = torch.randn(2, 3)
print(a)

b = torch.randn(3, 2)
print(b)

c = torch.mm(a, b)
print(c)

tensor([[ 1.3154, -0.7405,  0.0649],
        [-1.5538, -0.9745, -0.2570]])
tensor([[ 0.9923, -0.6349],
        [ 1.3119, -1.2179],
        [ 0.9985,  0.0490]])
tensor([[ 0.3986,  0.0699],
        [-3.0768,  2.1608]])


In [26]:
a = torch.randn(2, 3)
print(a)

b = torch.randn(3)
print(b)

c = torch.mv(a, b)
print(c)

tensor([[-1.1827, -0.2284, -0.6076],
        [-2.3583, -0.1161, -0.2655]])
tensor([-0.5223,  1.0817, -0.0165])
tensor([0.3807, 1.1104])


In [27]:
import torch
batch_n = 100
hidden_layer = 100
input_data = 1000
output_data = 10

In [28]:
#准备数据
x = torch.randn(batch_n, input_data)
y = torch.randn(batch_n, output_data)

#权重初始化
w1 = torch.randn(input_data, hidden_layer)
w2 = torch.randn(hidden_layer, output_data)

print(x.shape)
print(w1.shape)
print(w2.shape)
print(y.shape)

torch.Size([100, 1000])
torch.Size([1000, 100])
torch.Size([100, 10])
torch.Size([100, 10])


In [29]:
#设定后向传播次数和梯度下降的使用的学习速率
epoch_n = 20
learning_rate = 1e-6

In [31]:
#训练
for epoch in range(epoch_n):
    #前向传播
    h1 = x.mm(w1) #[100, 100]
    h1 = h1.clamp(min = 0) #使用clamp方法进行裁剪，将小于零的值全部重新赋值为0，这就像加上了一个ReLU激活函数的功能
    y_pred = h1.mm(w2) #[100, 10]

    #计算损失
    loss = (y_pred - y).pow(2).sum() #误差值的计算使用了均方误差函数
    print("Epoch:{}, Loss:{:.4f}".format(epoch, loss))

    #后向传播，计算梯度使用的是每个节点的链式求导结果
    grad_y_pred = 2 * (y_pred - y)
    grad_w2 = h1.t().mm(grad_y_pred)

    grad_h = grad_y_pred.clone()
    grad_h = grad_h.mm(w2.t())
    grad_h.clamp_(min=0)
    grad_w1 = x.t().mm(grad_h)

    #权重参数优化
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2

Epoch:0, Loss:45111212.0000
Epoch:1, Loss:103232624.0000
Epoch:2, Loss:407871424.0000
Epoch:3, Loss:792763008.0000
Epoch:4, Loss:61703608.0000
Epoch:5, Loss:21546258.0000
Epoch:6, Loss:11637468.0000
Epoch:7, Loss:7246638.5000
Epoch:8, Loss:4888881.0000
Epoch:9, Loss:3492946.5000
Epoch:10, Loss:2615785.7500
Epoch:11, Loss:2040769.0000
Epoch:12, Loss:1651443.8750
Epoch:13, Loss:1380337.6250
Epoch:14, Loss:1186384.5000
Epoch:15, Loss:1043831.0000
Epoch:16, Loss:936080.5000
Epoch:17, Loss:852307.0000
Epoch:18, Loss:785406.0000
Epoch:19, Loss:730626.6875


In [32]:
import torch
from torch.autograd import Variable
batch_n = 100
hidden_layer = 100
input_data = 1000
output_data = 10

#准备数据
x = Variable(torch.randn(batch_n, input_data), requires_grad = False)
y = Variable(torch.randn(batch_n, output_data), requires_grad = False)

#权重初始化
w1 = Variable(torch.randn(input_data, hidden_layer), requires_grad = True)
w2 = Variable(torch.randn(hidden_layer, output_data), requires_grad = True)

In [35]:
#设定后向传播的次数和梯度下降使用的学习速率。
epoch_n = 20
learning_rate = 1e-6

#训练
for epoch in range(epoch_n):
    #前向传播
    y_pred = x.mm(w1).clamp(min = 0).mm(w2)

    #计算损失
    loss = (y_pred - y).pow(2).sum() #误差值的计算使用了均方误差函数
    print("Epoch:{}, Loss:{:.4f}".format(epoch, loss))

    #后向传播
    loss.backward()

    #权重参数更新
    w1.data -= learning_rate * w1.grad.data
    w2.data -= learning_rate * w2.grad.data

    w1.grad.data.zero_()
    w2.grad.data.zero_()


Epoch:0, Loss:66450848.0000
Epoch:1, Loss:40079180.0000
Epoch:2, Loss:131765120.0000
Epoch:3, Loss:355795648.0000
Epoch:4, Loss:353228416.0000
Epoch:5, Loss:14694012.0000
Epoch:6, Loss:4048866.7500
Epoch:7, Loss:1890994.1250
Epoch:8, Loss:1282068.6250
Epoch:9, Loss:1048064.3125
Epoch:10, Loss:918042.5000
Epoch:11, Loss:823696.2500
Epoch:12, Loss:746386.4375
Epoch:13, Loss:680228.5000
Epoch:14, Loss:622553.5625
Epoch:15, Loss:571764.5000
Epoch:16, Loss:526797.1875
Epoch:17, Loss:486808.8125
Epoch:18, Loss:451019.2500
Epoch:19, Loss:418922.0625


In [36]:
import torch
from torch.autograd import Variable
batch_n = 100
hidden_layer = 100
input_data = 1000
output_data = 10

In [37]:
class Model(torch.nn.Module):
    def _init_(self):
        super(Model, self)._init_()

    def forward(self, input, w1, w2):
        x = torch.mm(input, w1)
        x = torch.clamp(x, min = 0)
        x = torch.mm(x, w2)
        return x

    def backward(self):
        pass
    

In [38]:
model = Model()

In [39]:
#准备数据
x = Variable(torch.randn(batch_n, input_data), requires_grad = False)
y = Variable(torch.randn(batch_n, output_data), requires_grad = False)

#权重初始化
w1 = Variable(torch.randn(input_data, hidden_layer), requires_grad = True)
w2 = Variable(torch.randn(hidden_layer, output_data), requires_grad = True)

#设定后向传播的次数和梯度下降使用的学习速率。
epoch_n = 20
learning_rate = 1e-6

#训练
for epoch in range(epoch_n):
    #前向传播
    y_pred = model(x, w1, w2)

    #计算损失
    loss = (y_pred - y).pow(2).sum() #误差值的计算使用了均方误差函数
    print("Epoch:{}, Loss:{:.4f}".format(epoch, loss))

    #后向传播
    loss.backward()

    #权重参数更新
    w1.data -= learning_rate * w1.grad.data
    w2.data -= learning_rate * w2.grad.data

    w1.grad.data.zero_() #梯度值置零
    w2.grad.data.zero_() #梯度值置零

Epoch:0, Loss:52473192.0000
Epoch:1, Loss:140658208.0000
Epoch:2, Loss:643584704.0000
Epoch:3, Loss:919177536.0000
Epoch:4, Loss:3908166.2500
Epoch:5, Loss:3191883.5000
Epoch:6, Loss:2662777.7500
Epoch:7, Loss:2258555.7500
Epoch:8, Loss:1942958.3750
Epoch:9, Loss:1690243.5000
Epoch:10, Loss:1484377.7500
Epoch:11, Loss:1314682.3750
Epoch:12, Loss:1173212.1250
Epoch:13, Loss:1053919.0000
Epoch:14, Loss:952304.5000
Epoch:15, Loss:865084.8125
Epoch:16, Loss:789755.8750
Epoch:17, Loss:724354.5625
Epoch:18, Loss:667238.9375
Epoch:19, Loss:617089.2500


In [43]:
import torch
from torch.autograd import Variable
batch_n = 100
hidden_layer = 100
input_data = 1000
output_data = 10

#准备数据
x = Variable(torch.randn(batch_n, input_data), requires_grad = False)
y = Variable(torch.randn(batch_n, output_data), requires_grad = False)

In [44]:
modles = torch.nn.Sequential(
    torch.nn.Linear(input_data, hidden_layer),
    torch.nn.ReLU(),
    torch.nn.Linear(hidden_layer, output_data)
)

In [45]:
hidden_layer = 100
input_data = 1000
output_data = 10

models = torch.nn.Sequential(
    torch.nn.Linear(input_data, hidden_layer),
    torch.nn.ReLU(),
    torch.nn.Linear(hidden_layer, output_data)
)
print(models)

Sequential(
  (0): Linear(in_features=1000, out_features=100, bias=True)
  (1): ReLU()
  (2): Linear(in_features=100, out_features=10, bias=True)
)


In [46]:
hidden_layer = 100
input_data = 1000
output_data = 10

from collections import OrderedDict
models = torch.nn.Sequential(OrderedDict([
    ("Line1", torch.nn.Linear(input_data, hidden_layer)),
    ("Relu1", torch.nn.ReLU()),
    ("Line2", torch.nn.Linear(hidden_layer, output_data))])
)
print(models)

Sequential(
  (Line1): Linear(in_features=1000, out_features=100, bias=True)
  (Relu1): ReLU()
  (Line2): Linear(in_features=100, out_features=10, bias=True)
)


In [48]:
#设定后向传播的次数和梯度下降使用的学习速率。
epoch_n = 10000
learning_rate = 1e-4

#定义损失函数
loss_fn = torch.nn.MSELoss()

In [50]:
import torch
from torch.autograd import Variable
loss_f = torch.nn.MSELoss()
# x = Variable(torch.randn(100, 100))
# y = Variable(torch.randn(100, 100))

x = Variable(torch.FloatTensor([1, 2, 3]))
y = Variable(torch.FloatTensor([0, 0, 0]))
loss = loss_f(x, y)
print(loss)

tensor(4.6667)


In [51]:
import torch
from torch.autograd import Variable
loss_f = torch.nn.L1Loss()
# x = Variable(torch.randn(100, 100))
# y = Variable(torch.randn(100, 100))

x = Variable(torch.FloatTensor([1, 2, 4]))
y = Variable(torch.FloatTensor([0, 0, 0]))
loss = loss_f(x, y)
print(loss)

tensor(2.3333)


In [55]:
import torch
from torch.autograd import Variable
loss_f = torch.nn.CrossEntropyLoss()
x = Variable(torch.randn(3, 5))
print(x)
y = Variable(torch.LongTensor(3).random_(5))
print(y)
# x = Variable(torch.FloatTensor([[1, 2], [3, 2]]))
# y = Variable(torch.LongTensor([1, 0]))
loss = loss_f(x, y)
print(loss)

tensor([[-0.5518,  1.0137,  0.6885,  0.3818, -1.8341],
        [ 1.8350,  1.8512, -0.0334,  1.3477, -0.5274],
        [-0.7465,  0.6282, -0.3037,  0.4175,  0.1192]])
tensor([3, 1, 0])
tensor(1.6967)


In [57]:
import torch
from torch.autograd import Variable
batch_n = 100
hidden = 100
input_data = 1000
output_data = 10

#准备数据
x = Variable(torch.randn(batch_n, input_data), requires_grad = False)
y = Variable(torch.randn(batch_n, output_data), requires_grad = False)

#定义模型
models = torch.nn.Sequential(
    torch.nn.Linear(input_data, hidden_layer),
    torch.nn.ReLU(),
    torch.nn.Linear(hidden_layer, output_data)
)

#设定后向传播的次数和梯度下降使用的学习速率。
epoch = 10000
learning_rata = 1e-4

#定义损失函数
loss_fn = torch.nn.MSELoss()

#训练
for epoch in range(epoch_n):
    #前向传播
    y_pred = models(x)

    #计算损失
    loss = loss_fn(y_pred, y)
    if epoch % 1000 == 0:
        print("Epoch:{}, Loss:{:.4f}".format(epoch, loss))
    models.zero_grad()

    #后向传播
    loss.backward()

    #权重参数更新
    for param in models.parameters():
        param.data -= param.grad.data * learning_rate

Epoch:0, Loss:1.1050
Epoch:1000, Loss:1.0220
Epoch:2000, Loss:0.9513
Epoch:3000, Loss:0.8895
Epoch:4000, Loss:0.8340
Epoch:5000, Loss:0.7840
Epoch:6000, Loss:0.7381
Epoch:7000, Loss:0.6954
Epoch:8000, Loss:0.6554
Epoch:9000, Loss:0.6179


In [60]:
import torch
from torch.autograd import Variable
batch_n = 100
hidden_layer = 100
input_data = 1000
output_data = 10

#准备数据
x = Variable(torch.randn(batch_n, input_data), requires_grad = False)
y = Variable(torch.randn(batch_n, output_data), requires_grad = False)

#定义模型
models = torch.nn.Sequential(
    torch.nn.Linear(input_data, hidden_layer),
    torch.nn.ReLU(),
    torch.nn.Linear(hidden_layer, output_data)
)

#设定后向传播的次数和梯度下降使用的学习速率。
epoch_n = 20
learning_rate = 1e-4

#定义损失函数
loss_fn = torch.nn.MSELoss()

#定义优化方法
optimzer = torch.optim.Adam(models.parameters(), lr = learning_rate)

#训练
for epoch in range(epoch_n):
    #前向传播
    y_pred = models(x)

    #计算损失
    loss = loss_fn(y_pred, y)
    print("Epoch:{}, Loss:{:4f}".format(epoch, loss))
    optimzer.zero_grad()

    #后向传播
    loss.backward()

    optimzer.step()

Epoch:0, Loss:1.041385
Epoch:1, Loss:1.020102
Epoch:2, Loss:0.999283
Epoch:3, Loss:0.979022
Epoch:4, Loss:0.959256
Epoch:5, Loss:0.939957
Epoch:6, Loss:0.921131
Epoch:7, Loss:0.902792
Epoch:8, Loss:0.884848
Epoch:9, Loss:0.867296
Epoch:10, Loss:0.850207
Epoch:11, Loss:0.833551
Epoch:12, Loss:0.817288
Epoch:13, Loss:0.801372
Epoch:14, Loss:0.785842
Epoch:15, Loss:0.770737
Epoch:16, Loss:0.755970
Epoch:17, Loss:0.741493
Epoch:18, Loss:0.727302
Epoch:19, Loss:0.713408
